image: python:3.8

stages:
  - lint
  - test
  - publish

application-lint-black:
  stage: lint
  script:
    - pip install black
    - black --check src/

application-lint-flake8:
  stage: lint
  script:
    - pip install flake8 pep8-naming
    - flake8 src/
    
application-lint-mypy:
  stage: lint
  script:
    - pip install mypy==0.790
    - mypy src/

application-lint-pydocstyle:
  stage: lint
  script:
    - pip install pydocstyle
    - pydocstyle src/

application-lint-darglint:
  stage: lint
  script:
    - pip install darglint
    - darglint src/

application-publish:
  stage: publish
  script:
    - pip install poetry==1.1.4
    - poetry config repositories.paaliaq https://gitlab.paaliaq.xyz/api/v4/projects/24/packages/pypi
    - poetry version $CI_COMMIT_TAG
    - poetry publish -r paaliaq --build -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  rules:
    - if: '$CI_COMMIT_TAG'