image: ubuntu:latest

stages:
  - linting
  - test
  
include:
  - template: Code-Quality.gitlab-ci.yml

application-test-release:
  stage: linting
  script:
    - apt update
    - apt -y install pip
    - pip install black
    - black --check src/

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]
