image: ubuntu:latest

stages:
  - build
  - test
  - publish
  - deploy

include:
  - template: Code-Quality.gitlab-ci.yml

application-build-release:
  stage: build
  script:
    - docker build -t "$CONTAINER_DEV_IMAGE" .
    - docker push "$CONTAINER_DEV_IMAGE"
  rules:
    - if: '$CI_COMMIT_TAG' 

application-test-release:
  stage: test
  script:
    - docker network create testnetwork 
    - docker run -d --net testnetwork --name mongoc mongo
    - docker run --net testnetwork "$CONTAINER_DEV_IMAGE" config.test.json
  rules:
    - if: '$CI_COMMIT_TAG' 

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]
